/**
 * Word Bank for Auto-Correction
 * Contains mappings for:
 * 1. Gen Z Slang / Internet abbreviations
 * 2. Hinglish Normalization (Common chat spellings -> Formal/Standard)
 * 3. Indian Common Names (Lowercase/Typos -> Proper Case)
 * 4. Locations & Castes
 * 5. Finance, Govt, Tech, Memes, and Regional Dialects
 */

export const WORD_BANK: Record<string, string> = {
    // --- GEN Z / INTERNET SLANG ---
    "plz": "please",
    "pls": "please",
    "thx": "thanks",
    "thnx": "thanks",
    "tysm": "thank you so much",
    "bcoz": "because",
    "cuz": "because",
    "coz": "because",
    "rn": "right now",
    "fr": "for real",
    "ong": "on god",
    "ngl": "not gonna lie",
    "tbh": "to be honest",
    "idk": "I don't know",
    "idc": "I don't care",
    "btw": "by the way",
    "imo": "in my opinion",
    "imho": "in my humble opinion",
    "wbu": "what about you",
    "hbu": "how about you",
    "lol": "laughing out loud",
    "lmao": "laughing my ass off",
    "rofl": "rolling on the floor laughing",
    "jk": "just kidding",
    "nvm": "never mind",
    "smh": "shaking my head",
    "fyi": "for your information",
    "asap": "as soon as possible",
    "aka": "also known as",
    "diy": "do it yourself",
    "faq": "frequently asked questions",
    "rip": "rest in peace",
    "pov": "point of view",
    "sus": "suspicious",
    "cap": "lie",
    "no cap": "no lie",
    "bet": "okay",
    "drip": "style",
    "finna": "going to",
    "gonna": "going to",
    "wanna": "want to",
    "gotta": "got to",
    "lemme": "let me",
    "gimme": "give me",
  
    // --- INDIAN ENGLISH PHONETIC CORRECTIONS ---
    "wideo": "video",
    "willage": "village",
    "walue": "value",
    "wery": "very",
    "wisit": "visit",
    "woice": "voice",
    "west": "vest",
    "wat": "what",
    "wen": "when",
    "wer": "where",
    "dat": "that",
    "dis": "this",
    "der": "there",
    "dose": "those",
    "tink": "think",
    "tank": "thank",
    "ting": "thing",
    "nating": "nothing",
    "everyting": "everything",
  
    // --- HINGLISH NORMALIZATION ---
    "nhi": "nahi",
    "nai": "nahi",
    "na": "na",
    "ha": "haan",
    "haan": "haan",
    "kese": "kaise",
    "kse": "kaise",
    "ese": "aise",
    "wese": "waise",
    "kyu": "kyun",
    "kyon": "kyun",
    "me": "mein",
    "mai": "main",
    "hum": "hum",
    "tum": "tum",
    "aap": "aap",
    "tera": "tera",
    "mera": "mera",
    "uska": "uska",
    "iska": "iska",
    "karna": "karna",
    "krna": "karna",
    "kr": "kar",
    "kar": "kar",
    "raha": "raha",
    "rha": "raha",
    "rhe": "rahe",
    "rhi": "rahi",
    "tha": "tha",
    "thi": "thi",
    "the": "the",
    "h": "hai",
    "hai": "hai",
    "he": "hai",
    "hun": "hoon",
    "hu": "hoon",
    "ho": "ho",
    "baat": "baat",
    "bat": "baat",
    "kuch": "kuch",
    "kch": "kuch",
    "bahut": "bahut",
    "bht": "bahut",
    "bohot": "bahut",
    "accha": "achha",
    "acha": "achha",
    "thik": "theek",
    "theek": "theek",
    "thk": "theek",
    "samajh": "samajh",
    "smjh": "samajh",
    "pyar": "pyaar",
    "pyaar": "pyaar",
    "dost": "dost",
    "bhai": "bhai",
    "bhaya": "bhaiya",
    "bahiya": "bhaiya",
    "behen": "behen",
    "did": "didi",
    "mummy": "mummy",
    "papa": "papa",
    "pita": "pita",
    "maa": "maa",
    "mata": "mata",
    "bhagwan": "bhagwan",
    "allah": "Allah",
    "khuda": "Khuda",
    "ishwar": "Ishwar",
    "waqt": "waqt",
    "wkt": "waqt",
    "samay": "samay",
    "jagah": "jagah",
    "jgh": "jagah",
    "duniya": "duniya",
    "zindagi": "zindagi",
    "jindagi": "zindagi",
    "khushi": "khushi",
    "gam": "gham",
    "paisa": "paisa",
    "rupad": "rupya",
    "kaam": "kaam",
    "kam": "kaam",
    "naam": "naam",
    "nam": "naam",
    "subah": "subah",
    "sham": "shaam",
    "raat": "raat",
    "din": "din",
    "aaj": "aaj",
    "kal": "kal",
    "parso": "parson",
    "kabhi": "kabhi",
    "abhi": "abhi",
    "jb": "jab",
    "tb": "tab",
    "kb": "kab",
    "sab": "sab",
    "sb": "sab",
    "sirf": "sirf",
    "bas": "bas",
    "bs": "bas",
    "aur": "aur",
    "or": "aur",
    "lekin": "lekin",
    "lkn": "lekin",
    "magar": "magar",
    "par": "par",
    "kyunki": "kyunki",
    "agar": "agar",
    "agr": "agar",
    "shayas": "shayad",
    "shayad": "shayad",
    "zaroor": "zaroor",
    "jarur": "zaroor",
    "bilkul": "bilkul",
    "blk": "bilkul",
    "sahi": "sahi",
    "galat": "galat",
    "glt": "galat",
    "kon": "kaun",
    "kaun": "kaun",
    "kya": "kya",
    "ky": "kya",
    "kidhar": "kidhar",
    "kaha": "kahan",
    "kahan": "kahan",
    "waha": "wahan",
    "wahan": "wahan",
    "yaha": "yahan",
    "yahan": "yahan",
  
    // --- INDIAN NAMES (Standardization) ---
    // Hindu
    "rahul": "Rahul",
    "rohit": "Rohit",
    "amit": "Amit",
    "sumit": "Sumit",
    "priya": "Priya",
    "pooja": "Pooja",
    "neha": "Neha",
    "sneha": "Sneha",
    "anjali": "Anjali",
    "arjun": "Arjun",
    "karan": "Karan",
    "vikram": "Vikram",
    "sanjay": "Sanjay",
    "raj": "Raj",
    "rajesh": "Rajesh",
    "suresh": "Suresh",
    "ram": "Ram",
    "shyam": "Shyam",
    "krishna": "Krishna",
    "shiv": "Shiv",
    "ganesh": "Ganesh",
    "lakshmi": "Lakshmi",
    "saraswati": "Saraswati",
    "durga": "Durga",
    "kali": "Kali",
    "sharma": "Sharma",
    "verma": "Verma",
    "gupta": "Gupta",
    "singh": "Singh",
    "kumar": "Kumar",
    "mishra": "Mishra",
    "tiwari": "Tiwari",
    "yadav": "Yadav",
    "patel": "Patel",
    "joshi": "Joshi",
    "mehta": "Mehta",
    "shah": "Shah",
    "agarwal": "Agarwal",
    "jain": "Jain",
    "reddy": "Reddy",
    "rao": "Rao",
    "nair": "Nair",
    "pillai": "Pillai",
    "iyer": "Iyer",
    "iyengar": "Iyengar",
    
    // Muslim
    "mohammed": "Mohammed",
    "mohd": "Mohammed",
    "md": "Mohammed",
    "ahmed": "Ahmed",
    "ali": "Ali",
    "hassan": "Hassan",
    "hussain": "Hussain",
    "khan": "Khan",
    "pathan": "Pathan",
    "shaikh": "Shaikh",
    "sheikh": "Sheikh",
    "siddiqui": "Siddiqui",
    "ansari": "Ansari",
    "qureshi": "Qureshi",
    "fatima": "Fatima",
    "ayesha": "Ayesha",
    "sana": "Sana",
    "zara": "Zara",
    "ibrahim": "Ibrahim",
    "yusuf": "Yusuf",
    "ismail": "Ismail",
    "abdullah": "Abdullah",
    "abdul": "Abdul",
    "rahman": "Rahman",
    "rahim": "Rahim",
    "karim": "Karim",
    
    // Sikh
    "gurpreet": "Gurpreet",
    "harpreet": "Harpreet",
    "manpreet": "Manpreet",
    "simran": "Simran",
    "jaspreet": "Jaspreet",
    "sukhwinder": "Sukhwinder",
    "satnam": "Satnam",
    "balwinder": "Balwinder",
    "kaur": "Kaur",
    "sardar": "Sardar",
    "khalsa": "Khalsa",
    
    // Christian
    "john": "John",
    "joseph": "Joseph",
    "thomas": "Thomas",
    "mathew": "Mathew",
    "george": "George",
    "mary": "Mary",
    "rose": "Rose",
    "anthony": "Anthony",
    "fernandes": "Fernandes",
    "dsouza": "D'Souza",
    "pereira": "Pereira",
    "rodrigues": "Rodrigues",
    
    // Parsi
    "tata": "Tata",
    "godrej": "Godrej",
    "mistry": "Mistry",
    "wadia": "Wadia",
    "irani": "Irani",
    
    // --- INDIAN LOCATIONS ---
    "delhi": "Delhi",
    "dilli": "Delhi",
    "new delhi": "New Delhi",
    "mumbai": "Mumbai",
    "bombay": "Mumbai",
    "bambai": "Mumbai",
    "kolkata": "Kolkata",
    "calcutta": "Kolkata",
    "chennai": "Chennai",
    "madras": "Chennai",
    "bengaluru": "Bengaluru",
    "bangalore": "Bangalore",
    "bglr": "Bangalore",
    "hyderabad": "Hyderabad",
    "pune": "Pune",
    "ahmedabad": "Ahmedabad",
    "jaipur": "Jaipur",
    "lucknow": "Lucknow",
    "kanpur": "Kanpur",
    "nagpur": "Nagpur",
    "indore": "Indore",
    "bhopal": "Bhopal",
    "patna": "Patna",
    "vadodara": "Vadodara",
    "surat": "Surat",
    "ludhiana": "Ludhiana",
    "agra": "Agra",
    "nashik": "Nashik",
    "varanasi": "Varanasi",
    "banaras": "Varanasi",
    "kashi": "Kashi",
    "amritsar": "Amritsar",
    "chandigarh": "Chandigarh",
    "goa": "Goa",
    "kerala": "Kerala",
    "punjab": "Punjab",
    "haryana": "Haryana",
    "gujarat": "Gujarat",
    "maharashtra": "Maharashtra",
    "rajasthan": "Rajasthan",
    "up": "Uttar Pradesh",

    // --- FINANCE & WORLD FINANCE ---
    "sensex": "Sensex",
    "nifty": "Nifty",
    "ipo": "IPO",
    "sip": "SIP",
    "fd": "FD",
    "mutual fund": "Mutual Fund",
    "stock market": "Stock Market",
    "share market": "Share Market",
    "bull run": "Bull Run",
    "bear market": "Bear Market",
    "recession": "Recession",
    "inflation": "Inflation",
    "gdp": "GDP",
    "gst": "GST",
    "itr": "ITR",
    "bitcoin": "Bitcoin",
    "crypto": "Crypto",
    "blockchain": "Blockchain",
    "ethereum": "Ethereum",
    "forex": "Forex",
    "nasdaq": "NASDAQ",
    "dow jones": "Dow Jones",
    "wall street": "Wall Street",
    "dalal street": "Dalal Street",
    "portfolio": "Portfolio",
    "dividend": "Dividend",

    // --- BANKING & PAYMENTS ---
    "upi": "UPI",
    "paytm": "Paytm",
    "gpay": "GPay",
    "phonepe": "PhonePe",
    "bhim": "BHIM",
    "qr code": "QR Code",
    "neft": "NEFT",
    "rtgs": "RTGS",
    "imps": "IMPS",
    "kyc": "KYC",
    "otp": "OTP",
    "cvv": "CVV",
    "atm": "ATM",
    "sbi": "SBI",
    "hdfc": "HDFC",
    "icici": "ICICI",
    "axis bank": "Axis Bank",
    "pnb": "PNB",
    "bob": "BoB",
    "kotak": "Kotak",
    "rbi": "RBI",
    "cibil": "CIBIL",
    "emi": "EMI",
    "loan": "Loan",
    "credit card": "Credit Card",
    "debit card": "Debit Card",
    "passbook": "Passbook",
    "cheque": "Cheque",

    // --- INDIAN GOVERNMENT & POLITICS ---
    "aadhar": "Aadhar",
    "adhar": "Aadhar",
    "pan card": "PAN Card",
    "passport": "Passport",
    "voter id": "Voter ID",
    "ration card": "Ration Card",
    "bjp": "BJP",
    "congress": "Congress",
    "modi": "Modi",
    "pm": "PM",
    "cm": "CM",
    "mla": "MLA",
    "mp": "MP",
    "parliament": "Parliament",
    "lok sabha": "Lok Sabha",
    "rajya sabha": "Rajya Sabha",
    "vidhan sabha": "Vidhan Sabha",
    "yojna": "Yojna",
    "scheme": "Scheme",
    "swachh bharat": "Swachh Bharat",
    "make in india": "Make in India",
    "startup india": "Startup India",
    "digital india": "Digital India",
    "man ki baat": "Mann Ki Baat",

    // --- POP CULTURE, BOLLYWOOD & ENTERTAINMENT ---
    "bollywood": "Bollywood",
    "hollywood": "Hollywood",
    "tollywood": "Tollywood",
    "srk": "SRK",
    "shah rukh": "Shah Rukh",
    "salman": "Salman",
    "amir khan": "Aamir Khan",
    "amitabh": "Amitabh",
    "bachchan": "Bachchan",
    "bigg boss": "Bigg Boss",
    "kbc": "KBC",
    "ipl": "IPL",
    "cricket": "Cricket",
    "virat": "Virat",
    "kohli": "Kohli",
    "dhoni": "Dhoni",
    "rohit sharma": "Rohit Sharma",
    "sachin": "Sachin",
    "thala": "Thala",
    "netflix": "Netflix",
    "prime video": "Prime Video",
    "hotstar": "Hotstar",
    "ott": "OTT",
    "reels": "Reels",
    "shorts": "Shorts",
    "youtuber": "YouTuber",
    "influencer": "Influencer",
    "vlog": "Vlog",
    "podcast": "Podcast",
    "cringe": "Cringe",
    "viral": "Viral",
    "trend": "Trend",

    // --- LATEST TECH & AI ---
    "ai": "AI",
    "artificial intelligence": "Artificial Intelligence",
    "chatgpt": "ChatGPT",
    "gemini": "Gemini",
    "bard": "Bard",
    "copilot": "Copilot",
    "coding": "Coding",
    "python": "Python",
    "javascript": "JavaScript",
    "react": "React",
    "node": "Node",
    "cloud": "Cloud",
    "aws": "AWS",
    "azure": "Azure",
    "google cloud": "Google Cloud",
    "saas": "SaaS",
    "startup": "Startup",
    "unicorn": "Unicorn",
    "faang": "FAANG",
    "maang": "MAANG",
    "android": "Android",
    "ios": "iOS",
    "windows": "Windows",
    "mac": "Mac",
    "5g": "5G",
    "wifi": "WiFi",
    "bluetooth": "Bluetooth",
    "metaverse": "Metaverse",
    "vr": "VR",
    "ar": "AR",

    // --- MEMES & INTERNET SLANG (INDIAN CONTEXT) ---
    "moye moye": "Moye Moye",
    "elvish": "Elvish",
    "system": "Systum",
    "systum": "Systum",
    "bhupendra jogi": "Bhupendra Jogi",
    "aayien": "Aayien",
    "baigan": "Baigan",
    "chin tapak": "Chin Tapak Dam Dam",
    "just looking like a wow": "Just Looking Like A Wow",
    "so beautiful so elegant": "So Beautiful So Elegant",
    "binod": "Binod",
    "rasode me kaun tha": "Rasode Me Kaun Tha",
    "pawri": "Pawri",
    "op": "OP",
    "gg": "GG",
    "noob": "Noob",
    "bot": "Bot",

    // --- REGIONAL DIALECTS (COMMON WORDS) ---
    // Punjabi
    "paji": "Paji",
    "paaji": "Paaji",
    "pra": "Pra",
    "veere": "Veere",
    "gal": "Gal",
    "vadiya": "Vadiya",
    "vadia": "Vadiya",
    "changa": "Changa",
    "si": "Si",
    "kidda": "Kidda",
    "kiddan": "Kidda",
    "satsriakal": "Sat Sri Akal",
    "chak de": "Chak De",
    "balle balle": "Balle Balle",
    
    // Haryanvi
    "manne": "Manne",
    "tanne": "Tanne",
    "ke": "Ke",
    "kati": "Kati",
    "ib": "Ib",
    "kad": "Kad",
    "bhai sahab": "Bhai Sahab",
    "tau": "Tau",
    
    // Bhojpuri/Bihari
    "humra": "Humra",
    "tohra": "Tohra",
    "ka": "Ka",
    "ba": "Ba",
    "babu": "Babu",
    "bhaiya": "Bhaiya",
    "ka hal ba": "Ka Hal Ba",
    "thik ba": "Thik Ba",
    
    // Mumbaiya / Tapori
    "apun": "Apun",
    "bantai": "Bantai",
    "bachchi": "Bachchi",
    "scene": "Scene",
    "shot": "Shot",
    "public": "Public",
    "mandali": "Mandali",
    "khopcha": "Khopcha",
    "waat": "Waat",
    "load": "Load",
    "fatafat": "Fatafat",
    "bindass": "Bindass"
  };
